/**
 * AP3X Industries Configuration
 * Same core infrastructure — different industries.
 * Add new industries by adding a single object entry.
 */

export const industriesConfig = [
  {
    id: 'logistics-transport',
    name: 'Logistics & Transport',
    shortName: 'Logistics',
    tagline: 'End-to-End Freight & Delivery Intelligence',
    description: 'Transform logistics operations with real-time fleet visibility, AI-optimised routing, automated compliance, and digital proof of delivery — deployed on the AP3X core infrastructure.',
    icon: 'truck',
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-600',
    accentColor: '#00e5ff',
    brandName: 'FleetCore OS',
    coreSystem: 'Fleet Control OS + Driver PWA',
    metrics: [
      { label: 'Route Efficiency', value: '+34%', desc: 'AI-optimised routing' },
      { label: 'Fuel Savings', value: '18.3%', desc: 'Eco driving analysis' },
      { label: 'Compliance', value: '100%', desc: 'Automated DVSA' },
      { label: 'Delivery SLA', value: '96.4%', desc: 'On-time performance' },
    ],
    workflows: [
      'Automated dispatch & route optimisation',
      'Driver mobile app with offline job management',
      'DVSA tachograph & compliance automation',
      'Real-time customer ETA notifications',
      'Digital proof of delivery with e-signature',
    ],
    termColor: 'text-cyan-400',
    bgAccent: 'rgba(0,229,255,0.05)',
  },
  {
    id: 'healthcare-monitoring',
    name: 'Healthcare Monitoring',
    shortName: 'Healthcare',
    tagline: 'AI-Powered Patient & Staff Operations Intelligence',
    description: 'Digitise clinical workflows, monitor patient pathways in real-time, coordinate care teams, and automate compliance reporting — all on the same proven AP3X infrastructure.',
    icon: 'heart-pulse',
    color: 'green',
    gradient: 'from-green-500 to-teal-600',
    accentColor: '#22c55e',
    brandName: 'CareCore OS',
    coreSystem: 'Control OS + Staff PWA',
    metrics: [
      { label: 'Response Time', value: '-42%', desc: 'Critical alerts' },
      { label: 'Staff Efficiency', value: '+29%', desc: 'Task automation' },
      { label: 'Documentation', value: '100%', desc: 'Digital capture' },
      { label: 'Patient Flow', value: '+38%', desc: 'Pathway optimisation' },
    ],
    workflows: [
      'Real-time patient pathway monitoring dashboard',
      'Care staff mobile app with task management',
      'Automated CQC compliance documentation',
      'Medication and appointment workflow automation',
      'Incident reporting with escalation triggers',
    ],
    termColor: 'text-green-400',
    bgAccent: 'rgba(34,197,94,0.05)',
  },
  {
    id: 'mental-health-recovery',
    name: 'Mental Health Recovery',
    shortName: 'Mental Health',
    tagline: 'Continuous Recovery Support & Care Coordination',
    description: 'Support recovery journeys with structured daily check-ins, AI mood analysis, care team coordination, and crisis escalation — built on the same AP3X operational foundation.',
    icon: 'brain',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-600',
    accentColor: '#a855f7',
    brandName: 'MindCore OS',
    coreSystem: 'Control OS + Recovery PWA',
    metrics: [
      { label: 'Engagement Rate', value: '91%', desc: 'Daily check-ins' },
      { label: 'Crisis Prevention', value: '+67%', desc: 'Early intervention' },
      { label: 'Care Coordination', value: '+54%', desc: 'Team response' },
      { label: 'Recovery Tracking', value: '100%', desc: 'Digital continuity' },
    ],
    workflows: [
      'Daily mood check-in and symptom tracking PWA',
      'AI-powered pattern analysis and risk alerts',
      'Care team coordination and handover automation',
      'Crisis escalation with automated contact protocols',
      'Recovery milestone tracking and reporting',
    ],
    termColor: 'text-purple-400',
    bgAccent: 'rgba(168,85,247,0.05)',
  },
  {
    id: 'training-education',
    name: 'Training & Education',
    shortName: 'Education',
    tagline: 'Workforce Learning & Competency Management Intelligence',
    description: 'Manage training programmes, track learner progress, automate certification workflows, and deliver AI-assisted learning — all running on the AP3X operational core.',
    icon: 'graduation-cap',
    color: 'amber',
    gradient: 'from-amber-500 to-orange-600',
    accentColor: '#f59e0b',
    brandName: 'LearnCore OS',
    coreSystem: 'Control OS + Learner PWA',
    metrics: [
      { label: 'Completion Rate', value: '+47%', desc: 'Structured pathways' },
      { label: 'Admin Reduction', value: '-73%', desc: 'Automated workflows' },
      { label: 'Certification', value: '100%', desc: 'Digital tracking' },
      { label: 'Learner NPS', value: '89', desc: 'Satisfaction score' },
    ],
    workflows: [
      'Learner progression tracking and pathway management',
      'Mobile learning delivery with offline capability',
      'Automated certification and expiry management',
      'Trainer coordination and resource scheduling',
      'Compliance training reporting and audit trails',
    ],
    termColor: 'text-amber-400',
    bgAccent: 'rgba(245,158,11,0.05)',
  },
  {
    id: 'workforce-operations',
    name: 'Workforce Operations',
    shortName: 'Workforce',
    tagline: 'Intelligent Field Workforce Management & Coordination',
    description: 'Coordinate dispersed workforces, automate scheduling, track productivity, manage compliance, and deliver field operatives a powerful mobile workspace — on AP3X infrastructure.',
    icon: 'users',
    color: 'blue',
    gradient: 'from-blue-500 to-indigo-600',
    accentColor: '#3b82f6',
    brandName: 'WorkCore OS',
    coreSystem: 'Fleet Control OS + Worker PWA',
    metrics: [
      { label: 'Scheduling Efficiency', value: '+51%', desc: 'AI optimisation' },
      { label: 'Productivity Gain', value: '+33%', desc: 'Task automation' },
      { label: 'Payroll Accuracy', value: '99.9%', desc: 'Digital timesheets' },
      { label: 'Absence Reduction', value: '-28%', desc: 'Proactive management' },
    ],
    workflows: [
      'AI-powered shift scheduling and optimisation',
      'Field worker mobile app with job management',
      'Automated timesheet and payroll data capture',
      'Performance analytics and KPI dashboards',
      'HR compliance and documentation automation',
    ],
    termColor: 'text-blue-400',
    bgAccent: 'rgba(59,130,246,0.05)',
  },
]

export const getIndustryById = (id) => industriesConfig.find(i => i.id === id)
